2024-11-20T18:15:24.272458+0000 INFO 138131107692672 Created database engine for db quotesdbtest_whistleask, user quotesdbtest_whistleask, address pcyp4.h.filess.io:3307
2024-11-20T18:15:25.004058+0000 INFO 138131107692672 Database schema initialized successfully.
2024-11-20T18:15:25.088010+0000 INFO 138131107692672 Tables in the database: ['TestTable', 'authors', 'quotes', 'quotes_tags_link', 'tags', 'users']
2024-11-20T18:15:25.088499+0000 INFO 138131107692672 All required tables have been created successfully.
2024-11-20T18:15:25.347495+0000 INFO 138131107692672 All tables truncated successfully.
2024-11-20T18:15:25.411525+0000 INFO 138131107692672 Database initialized successfully with new records.
2024-11-20T18:15:29.419283+0000 ERROR 138131107692672 Error inserting row into users: (pymysql.err.OperationalError) (1054, "Unknown column 'time_updated' in 'field list'")
[SQL: INSERT INTO users (id, username, password, time_updated) VALUES (%(id)s, %(username)s, %(password)s, %(time_updated)s)]
[parameters: {'id': '2087b9f0-4d56-4562-a517-ead75097e02b', 'username': 'user1', 'password': '$2b$12$wAfSnUXZZDHxlyS.fsRDGeVGjdf8Kl98dLDmf8ilLke19HvqBU5R6', 'time_updated': None}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
